In [1]:
# Day 01 - NumPy Basics
# Author: Ayush Gupta
# Description: Learning NumPy for numerical operations in Machine Learning

import numpy as np

In [3]:
# Creating ARRays
# 1D Array
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [4]:
# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
# Using built-in functions
zeros = np.zeros((2,3))
ones = np.ones((2,2))
identity = np.eye(3)

print(zeros)
print(ones)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Attributes of Arrays
arr = np.array([[1,2,3],[4,5,6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


In [7]:
# Indexing and Slicing
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])        # First element
print(arr[-1])       # Last element
print(arr[1:4])      # Slicing

# 2D indexing
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0,1])     # Row 0, Column 1

10
50
[20 30 40]
2


In [8]:
# Array Operation
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

[5 7 9]


In [9]:
print(a - b)

[-3 -3 -3]


In [10]:
print(a * b)

[ 4 10 18]


In [11]:
print(a / b)

[0.25 0.4  0.5 ]


In [12]:
# Array Broadcasting
arr = np.array([1,2,3])
print(arr + 5)   # Adds 5 to each element

[6 7 8]


In [13]:
# Important Functions
arr = np.array([1,2,3,4,5])

print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

3.0
15
5
1
1.4142135623730951


In [14]:
# Array Reshaping
arr = np.array([1,2,3,4,5,6])

reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [15]:
# Random Numbers
rand = np.random.rand(3,3)        # Random between 0 and 1
rand_int = np.random.randint(1,10,(2,3))

print(rand)
print(rand_int)

[[0.22785918 0.46847459 0.28223005]
 [0.09522963 0.14216849 0.25675291]
 [0.79984783 0.4101814  0.96344534]]
[[2 3 4]
 [9 9 9]]


In [16]:
# Conditional Selection 
arr = np.array([10, 20, 30, 40])

print(arr > 20)
print(arr[arr > 20])

[False False  True  True]
[30 40]


In [17]:
arr = np.array([1,2,3])

copy_arr = arr.copy()
view_arr = arr.view()

arr[0] = 99

print("Original:", arr)
print("Copy:", copy_arr)
print("View:", view_arr)

Original: [99  2  3]
Copy: [1 2 3]
View: [99  2  3]
