In [1]:
# Day 03 - Vectors & Matrices

import numpy as np

In [2]:
# Creating a vector
vector = np.array([1, 2, 3])

print("Vector:", vector)

Vector: [1 2 3]


In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Addition
print("Addition:", v1 + v2)

# Subtraction
print("Subtraction:", v1 - v2)

# Scalar multiplication
print("Scalar Multiplication:", v1 * 2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Scalar Multiplication: [2 4 6]


In [4]:
# Dot Product
dot = np.dot(v1, v2)

print("Dot Product:", dot)

Dot Product: 32


In [5]:
# Creating a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Matrix:\n", matrix)

Matrix:
 [[1 2 3]
 [4 5 6]]


In [6]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

# Addition
print("Addition:\n", m1 + m2)

# Multiplication (element-wise)
print("Element-wise:\n", m1 * m2)

Addition:
 [[ 6  8]
 [10 12]]
Element-wise:
 [[ 5 12]
 [21 32]]


In [7]:
# Matrix multiplication
result = np.dot(m1, m2)

print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [8]:
# Transpose
transpose = m1.T

print("Transpose:\n", transpose)

Transpose:
 [[1 3]
 [2 4]]


In [9]:
print("Shape:", m1.shape)

Shape: (2, 2)
