## Singular Value Decomposition (SVD)

A matrix A can be decomposed as:

A = U Σ Vᵀ

Where:
- U → left singular vectors
- Σ → diagonal matrix (singular values)
- Vᵀ → right singular vectors

In [1]:
import numpy as np

A = np.array([[3, 1],
              [1, 3]])

print(A)

[[3 1]
 [1 3]]


In [2]:
# Step 1: Compute AᵀA
A_T = A.T
ATA = np.dot(A_T, A)

print("A^T A:\n", ATA)

A^T A:
 [[10  6]
 [ 6 10]]


In [3]:
eigenvalues, eigenvectors = np.linalg.eig(ATA)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [16.  4.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [4]:
# Singular Values
singular_values = np.sqrt(eigenvalues)

print("Singular Values:", singular_values)

Singular Values: [4. 2.]


In [5]:
# U = (A * V) / singular values
U = np.dot(A, eigenvectors)

print("U (approx):\n", U)

U (approx):
 [[ 2.82842712 -1.41421356]
 [ 2.82842712  1.41421356]]


## Understanding

- SVD breaks matrix into simpler parts
- Helps reduce dimensions
- Used in PCA, recommendation systems