In [1]:
# Day 03 - SVD using NumPy

import numpy as np

In [2]:
A = np.array([[3, 1],
              [1, 3]])

print("Matrix A:\n", A)

Matrix A:
 [[3 1]
 [1 3]]


In [3]:
# Applying SVD
U, S, VT = np.linalg.svd(A)

print("U:\n", U)
print("Singular Values:", S)
print("V^T:\n", VT)

U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular Values: [4. 2.]
V^T:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


## Output of SVD

U → left singular vectors  
S → singular values  
Vᵀ → right singular vectors  

A = U Σ Vᵀ

In [4]:
# Convert S to diagonal matrix
S_matrix = np.diag(S)

# Reconstruct A
A_reconstructed = np.dot(U, np.dot(S_matrix, VT))

print("Reconstructed A:\n", A_reconstructed)

Reconstructed A:
 [[3. 1.]
 [1. 3.]]


In [5]:
print("Original:\n", A)
print("\nReconstructed:\n", A_reconstructed)

Original:
 [[3 1]
 [1 3]]

Reconstructed:
 [[3. 1.]
 [1. 3.]]
