In [1]:
# Day 03 - Correlation & Covariance

import numpy as np
import pandas as pd

In [2]:
# Sample Data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])   # perfectly related x= 2y

df = pd.DataFrame({"X": x, "Y": y})
print(df)

   X   Y
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10


In [3]:
# Covariance
cov = np.cov(x, y)

print("Covariance Matrix:\n", cov)

Covariance Matrix:
 [[ 2.5  5. ]
 [ 5.  10. ]]


	•	Positive → variables increase together
	•	Negative → opposite movement

In [4]:
# Correlation
corr = np.corrcoef(x, y)

print("Correlation Matrix:\n", corr)

Correlation Matrix:
 [[1. 1.]
 [1. 1.]]


Value range:
	•	+1 → strong positive
	•	0 → no relation
	•	-1 → strong negative

In [5]:
# Correlation using pandas
print(df.corr())

     X    Y
X  1.0  1.0
Y  1.0  1.0


In [6]:
# Negative relation Example
y2 = np.array([10, 8, 6, 4, 2])

print(np.corrcoef(x, y2))

[[ 1. -1.]
 [-1.  1.]]


In [7]:
# Random data . No Relationship
y3 = np.random.rand(5)

print(np.corrcoef(x, y3))

[[1.        0.2913038]
 [0.2913038 1.       ]]


In [ ]:
# With Real Datasetx
df = pd.read_csv("data.csv")

print(df.corr(numeric_only=True))

                            loan_id   no_of_dependents   income_annum  \
loan_id                    1.000000           0.005326       0.012592   
 no_of_dependents          0.005326           1.000000       0.007266   
 income_annum              0.012592           0.007266       1.000000   
 loan_amount               0.008170          -0.003366       0.927470   
 loan_term                 0.009809          -0.020111       0.011488   
 cibil_score               0.016323          -0.009998      -0.023034   
 residential_assets_value  0.020936           0.007376       0.636841   
 commercial_assets_value   0.018595          -0.001531       0.640328   
 luxury_assets_value      -0.000862           0.002817       0.929145   
 bank_asset_value          0.010765           0.011163       0.851093   

                            loan_amount   loan_term   cibil_score  \
loan_id                        0.008170    0.009809      0.016323   
 no_of_dependents             -0.003366   -0.020111     -0

## Why Correlation & Covariance?

- Helps understand relationships between features
- Useful for feature selection
- Avoids redundant features